### ISSUE TITLE
Do you have a detailed installation guide

### ISSUE THREAD

**Issue by TheCanny41** [Kichi779/Twitch-Viewer-Bot#11]
I'm new to these issues, if you have a detailed installation guide, where can I find, for example, a video, a pdf ?

**Comment by Kichi779** [comment]
You asked about the detailed use of the program. Yes, detailed installation is basically available in the ⁠#detailed-installation-guide room on my discord server. I shared it in pdf form, you can click and provide the installation in detail. https://discord.gg/AFV9m8UXuT

**Comment by wizdom-nerd** [comment]
check out this working version: video link: https://www.youtube.com/watch?v=PDu2QQTgCZ4 
discord link: https://discord.gg/Uf5RPA8Vyr
