### ISSUE TITLE
Adult public streaming

### ISSUE THREAD

**Issue by Fede14it** [Kichi779/Twitch-Viewer-Bot#13]
Hi when you try to send viewers to a streming that have adult restrciton viewers aren't counted

**Comment by MaxdepoesGames** [comment]
got the same problem

**Comment by Kichi779** [comment]
Unfortunately, there is no solution, try removing headless and manually confirming

**Comment by wizdom-nerd** [comment]
check out this working version: video link: https://www.youtube.com/watch?v=PDu2QQTgCZ4 
discord link: https://discord.gg/Uf5RPA8Vyr
