### ISSUE TITLE
Error when setting low quality

### ISSUE THREAD

**Issue by LeonardoPereiraDaSilva** [Kichi779/Twitch-Viewer-Bot#15]
When I try to set the bot to run in low quality the attached error occurs.

It sends the viewers, but this error occurs and the program closes.

![Error](https://github.com/Kichi779/Twitch-Viewer-Bot/assets/139291819/c27a4fdf-1053-4e26-9032-089eb2ac7952)

**Comment by S1NJED** [comment]
same here

**Comment by Sabcoll** [comment]
guess it could be an easy fix with the selection of the correct class.
data-a-target="player-settings-menu-item-quality"

or something similar
