### ISSUE TITLE
Error when try to send viewers

### ISSUE THREAD

**Issue by Blur1971** [Kichi779/Twitch-Viewer-Bot#18]
![Screenshot_9](https://github.com/Kichi779/Twitch-Viewer-Bot/assets/150248544/c31c717b-2c4f-410c-80af-62889132c0e6)

**Comment by Blur1971** [comment]
Can you please helpme?

**Comment by Kichi779** [comment]
**The Chromedriver version and your google chrome version are not the same. Please install chromedriver, which is the same as your google chrome version, and then replace it with chromedriver.exe in the folder**

**Comment by Blur1971** [comment]
I will try thx a bunch

**Comment by Blur1971** [comment]
One question: when you say: "and then replace it with chromedriver.exe in the folder" which chromedriver should I replace in which folder?. Sorry for bothering you

**Comment by Blur1971** [comment]
Worked like a charm. Thanks again

**Comment by wizdom-nerd** [comment]
check out this working version: video link: https://www.youtube.com/watch?v=PDu2QQTgCZ4 
discord link: https://discord.gg/Uf5RPA8Vyr
