### ISSUE TITLE
There is a problem with the connecting to the twitch.

### ISSUE THREAD

**Issue by BloodCelebration** [Kichi779/Twitch-Viewer-Bot#19]
Does this seem to be unavailable now? I tried send viewer but it didn't work, then I went and tried connecting to the twitch directly from croxyproxy but the page reports an error and the whole browser crashes. I went on to try to connect to youtube and ins from croxyproxy, but no problem. It's only twitch that doesn't connect.

**Comment by Sabcoll** [comment]
Maybe twitch aready banned the proxy? Can someone confirm?

**Comment by Kichi779** [comment]
Proxy servers can be slow sometimes, unfortunately, there is no solution to this. You can try again another time free proxies are a bit like this
