### ISSUE TITLE
it stop working to twitch

### ISSUE THREAD

**Issue by zihuanfeng520** [Kichi779/Twitch-Viewer-Bot#20]
![image](https://github.com/Kichi779/Twitch-Viewer-Bot/assets/84898068/d4e449e3-65f4-4432-9e54-4fd2b252d93b)

it stuck on this after DevTools listening on ws://127.0.0.1:1314/devtools/browser/3e28af66-c401-4627-983d-a4472f868d99

how can i slove this

**Comment by Akasumi1998** [comment]
same here, i launch main.py for cmd but nothing

**Comment by Akasumi1998** [comment]
> i figured it out, you gotta set "reduce to 160p" to off, then it works


I am going to try

**Comment by wizdom-nerd** [comment]
check out this working version: video link: https://www.youtube.com/watch?v=PDu2QQTgCZ4 
discord link: https://discord.gg/Uf5RPA8Vyr
