### ISSUE TITLE
Error / Solved

### ISSUE THREAD

**Issue by Yerdeniiz** [Kichi779/Twitch-Viewer-Bot#3]
![resim_2023-03-24_174426344](https://user-images.githubusercontent.com/128812613/227557300-62f1222e-842c-45b5-8c4f-86d38ca8b1c7.png)
it closes after this screen

**Comment by ramune0144** [comment]
set chrome_path = 'your/chrome_path/chrome.exe'
ex :
`
chrome_path = r'C:\Users\user\AppData\Local\Google\Chrome\Application\chrome.exe'
`
