### ISSUE TITLE
Mac OS support

### ISSUE THREAD

**Issue by MrGoldWatch** [Kichi779/Twitch-Viewer-Bot#7]
I see some hardcoded paths that indicates this is a Windows only app. I tried changing the path to see if it works on Mac but had no luck.

So was wondering if its doable and if so how would one go about making that enhancement and potentially creating a PR.

Thanks

**Comment by MrGoldWatch** [comment]
@Kichi779 i have a fix ready, but i need permission to make a new branch and PR

**Comment by x3r4n0** [comment]
can u please fork this repo? im on macos too with m1 and im searching for this!

**Comment by MrGoldWatch** [comment]
@x3r4n0 i will give you access, but its a private repo since id like to just push to this code.
